Repository ytsruh/wrongmove, pull requests merged in 2023-01, with the labels that each got.

#71 Completed Agent Profile, Image form & agent nav
  README.md
  server/lib/schema.js
  server/lib/storage.js
  server/lib/utils.js
  server/routes/index.js
  server/routes/profile.js
  server/routes/sales.js
  src/assets/agent-logout.jpg
  src/assets/estate-office.jpg
  src/assets/sold.png
  src/components/AgentNav.jsx
  src/components/ImageForm.jsx
  src/components/UpdateForm.jsx
  src/hooks/useUpdateData.jsx
  src/pages/_app.js
  src/pages/agent/create-listing.jsx
  src/pages/agent/dashboard/index.jsx
  src/pages/agent/logout.jsx
  src/pages/agent/profile.jsx
  src/pages/agent/sales.jsx
  src/styles/agentNav.css
  src/styles/index.css
Labels: bug, new feature, front end, back end

#95 Completed edit listing page for sales listings
  src/pages/agent/edit-listing/[id].jsx
Labels: new feature, front end

#101 bug fix related to element positioning agent nav
  src/components/AgentNav.jsx
  src/styles/agentNav.css
  src/styles/index.css
Labels: front end

#102 Added Agent Navigation to Footer
  src/components/footer/Footer.jsx
Labels: front end

#109 Sales listing image
  package-lock.json
  package.json
  server/routes/sales.js
  src/components/DeleteImages.jsx
  src/pages/_app.js
  src/pages/agent/edit-listing/[id].jsx
  src/styles/images.css
  src/styles/index.css
Labels: new feature, front end

#110 Dashboard & Statistics Pages completed
  src/components/AgentStats.jsx
  src/pages/_app.js
  src/pages/agent/dashboard/index.jsx
  src/pages/agent/statistics.jsx
  src/styles/agentStats.css
Labels: new feature, front end

#112 Made page /public/sales/all which shows all sales listings
  src/assets/icons/listings/bath.png
  src/assets/icons/listings/bed.png
  src/components/DeleteImages.jsx
  src/pages/_app.js
  src/pages/public/sales/all.jsx
  src/styles/index.css
  src/styles/publicListings.css
  src/utils.js
Labels: new feature, front end

#114 Added agent rental functionality
  package.json
  src/components/AgentNav.jsx
  src/components/AgentStats.jsx
  src/components/DeleteImages.jsx
  src/pages/agent/create-listing.jsx
  src/pages/agent/edit-listing/[id].jsx
  src/pages/agent/index.jsx
  src/pages/agent/rentals/[id].jsx
  src/pages/agent/rentals/index.jsx
  src/pages/agent/sales/[id].jsx
  src/pages/agent/sales/index.jsx
  src/pages/login/agent/index.jsx
  src/utils.js
Labels: new feature, front end

#116 Added query string filtering to public api
  server/routes/public.js
Labels: new feature, back end

#117 Utility pages
  src/assets/404.jpeg
  src/assets/500.jpeg
  src/components/AgentStats.jsx
  src/pages/404.js
  src/pages/500.js
  src/pages/comingsoon.js
  src/styles/layout.css
Labels: bug, new feature, front end

#119 Fixed utility pages & added agents page
  server/routes/public.js
  src/assets/placeholder.png
  src/components/Nav.jsx
  src/hooks/usePublicData.jsx
  src/pages/404.js
  src/pages/500.js
  src/pages/_app.js
  src/pages/agents.jsx
  src/pages/comingsoon.jsx
  src/styles/agentCard.css
Labels: new feature, front end

#120 Single sales listing
  src/assets/icons/listings/house.png
  src/components/cards/AgentAd.jsx
  src/components/footer/Footer.jsx
  src/components/listings/Lightbox.jsx
  src/components/listings/ListingImages.jsx
  src/hooks/useFetchPublicData.jsx
  src/pages/_app.js
  src/pages/sales/[id].jsx
  src/pages/sales/index.jsx
  src/styles/card.css
  src/styles/index.css
  src/styles/lightbox.css
  src/styles/publicListings.css
  src/utils.js
Labels: new feature, front end

#121 Minor Bug Fixes and Tidy Up
  src/components/HomeContent.jsx
  src/components/Nav.jsx
  src/components/cards/AccountCard.jsx
  src/components/cards/AgentAd.jsx
  src/components/cards/BorderlessCard.jsx
  src/components/cards/MobileHomeLink.jsx
  src/components/cards/RecentSearch.jsx
  src/components/cards/WhereCanILive.jsx
  src/components/footer/Footer.jsx
  src/components/footer/FooterLink.jsx
  src/components/footer/FooterSection.jsx
  src/pages/agents.jsx
  src/pages/sales/index.jsx
  src/styles/nav.css
Labels: front end

#122 Added optional filters for /sales listings to frontend
  src/components/Dropdown.jsx
  src/components/Input.jsx
  src/pages/sales/index.jsx
  src/styles/index.css
Labels: new feature, front end
